name: nameApp
version: 0.0.1
log: false
vars: vars-local.yaml
tasks:
  createService: &createService
    - exist: ${serviceDir}/${serviceName}.service
    - echo: ${os} AND ${output}
    - if:
        type: equal
        value: linux AND false
        jobs:
          - echo: ${datetime} - createService
          - cmd: sudo service ${serviceName} stop
          - cmd: touch ${serviceName}.service
          - create-file:
              file: ${serviceDir}/${serviceName}.service
              content: |
                [ Unit ]
                Description=Service description
                After=network.target
                [Service]
                User=root
                Group=root
                ExecStart=${projectDir}/seed-linux
                Restart=on-failure
                [Install]
                WantedBy=multi-user.target
          - cmd: sudo systemctl daemon-reload
          - cmd: sudo service ${serviceName} restart
          - stop: true
  configServer: &configServer
    - echo: ${datetime} - configServer
    - kill-port: ${port}
    - create-file:
        file: ${projectDir}/continuous-seed-test/config.js
        content: |
          export const config = {
              name:"${name}",
              environment:"${environment}",
              port:${port}
          }
    - cmd:
        app: npm
        args: install
        workingDirectory: ${projectDir}/continuous-seed-test/
    - cmd:
        app: npm
        args: start
        workingDirectory: ${projectDir}/continuous-seed-test/
        background: true
jobs:
  - createService: *createService
  - cloneRepo:
      - echo: ${datetime} - cloneRepo
      - cmd: git clone ${branch}
      - configServer: *configServer
  - checkUpdates:
      - echo: ${datetime} - checkUpdates
      - loop:
          interval: 10000
          jobs:
            - cmd: git -C ${projectDir}/continuous-seed-test reset --hard
            - cmd: git -C ${projectDir}/continuous-seed-test pull
            - if:
                type: contain!
                value: Already up to date
                jobs:
                  - configServer: *configServer