name: nameApp
version: 0.0.1
log: true
vars:
  domain: localhost
  port: 4000
  databaseHost: localhost
  databasePort: 3306
  databaseName: mha_test
  databaseUser: root
  databasePass: root
  workDir: /Users/tufikchediak/mega/server/projects/cloudbit/repositories/continuous
  serviceDir: /Users/tufikchediak/mega/server/projects/cloudbit/repositories/continuous/fakeServicesDir
  migrationFile: migration-mac-amd64
tasks:
  createService: &createService
    - cmd: mkdir ${serviceDir}
    - cmd: if [ -f ${serviceDir}/continuous.service ] ; then echo 1 ; else echo 0 ; fi
    - if:
       type: equal
       value: 0
       jobs:
#         - cmd: sudo systemctl stop continuous
          - cmd: touch continuous.service
          - cmd: |
             echo '
               [Unit]
               Description=instance to serve api
               After=network.target
               [Service]
               User=root
               Group=root
               ExecStart=${workDir}/continuous
               [Install]
               WantedBy=multi-user.target
             ' > continuous.service
          - cmd: mv continuous.service ${serviceDir}/continuous.service
#         - cmd: sudo systemctl daemon-reload
#          - cmd: sudo systemctl start continuous
          - stop: true
  updateDB: &updateDB
    - cmd: touch ${workDir}/mha/db/migration/config.env
    - cmd: |
        echo '
         DB_HOST = ${databaseHost}
         DB_PORT = ${databasePort}
         DB_NAME = ${databaseName}
         DB_USER = ${databaseUser}
         DB_PASSWORD = ${databasePass}
         FILES_PATH = sqlFiles/
         EXIT = true
         FILES_SORT = UPDATE_DATE_ASC
        ' > ${workDir}/mha/db/migration/config.env
    - cmd: ${workDir}/mha/db/migration/${migrationFile}
  updateServer: &updateServer
    - cmd:
        app: npm
        args: "i"
        workingDir: "${workDir}/mha/server/"
    - cmd: touch ${workDir}/mha/server/config.js
    - cmd: |
        echo '
         export const config = {
            version:"0.0.1",
            environment:"L",
            domain:"${domain}",
            port:4000,
            databaseHost:"${databaseHost}",
            databasePort:"${databasePort}",
            databaseName:"${databaseName}",
            databaseUser:"${databaseUser}",
            databasePass:"${databasePass}",
          }
        ' > ${workDir}/mha/server/config.js
    - cmd:
        app: npm
        args: install
        workingDirectory: ${workDir}/mha/server
    - cmd:
        app: npm
        args: run stop
        workingDirectory: ${workDir}/mha/server
    - cmd:
        app: npm
        args: run server
        workingDirectory: ${workDir}/mha/server
jobs:
  - createService: *createService
  - cloneRepo:
      - cmd: git clone -b master https://tufik_chediak:ATBBfTrSHKGTHDQMNwWBLsYBVAnaC774C627@bitbucket.org/refinedrisk/risk-mental-health-app.git ${workDir}/mha
      - updateDB: *updateDB
      - updateServer: *updateServer
  - checkUpdates:
      - loop:
          sleepTime: 10000
          jobs:
            - cmd: git -C ${workDir}/mha pull
            - if:
                type: contain!
                value: Already up to date
                jobs:
                  - updateDB: *updateDB
                  - updateServer: *updateServer