name: nameApp
version: 0.0.1
port: 9184
vars:
  domain: localhost
  port: 4000
  databaseHost: localhost
  databasePort: 3306
  databaseName: mha
  databaseUser: root
  databasePass: root
  workDir: ./mhaServer
  serviceDir: ./fakeServicesDir
jobs:
  - createService:
    - cmd: if [ -f {serviceDir}/continuous.service ] ; then echo 1 ; else echo 0 ; fi
    - if:
        type: equal
        value: 0
        jobs:
          - cmd: echo "HELLO"
