name: nameApp
version: 0.0.1
log: false
vars:
  name: Test App
  environment: staging
  port: 4000
  branch: main
  projectDir: C:/tufik/seed
tasks:
  configServer: &configServer
    - echo: ${datetime} - configServer
    - kill-port: ${port}
    - create-file:
        file: ${projectDir}/continuous-seed-test/config.js
        content: |
          export const config = {
              name:"${name}",
              environment:"${environment}",
              port:${port}
          }
    - cmd:
        app: npm
        args: install
        workingDirectory: ${projectDir}/continuous-seed-test/
    - cmd:
        app: npm
        args: start
        workingDirectory: ${projectDir}/continuous-seed-test/
        background: mhaProcess
jobs:
  - cloneRepo:
      - echo: ${datetime} - cloneRepo
      - cmd:
          app: git
          args: clone -b ${branch} https://github.com/cloudbit-interactive/continuous-seed-test.git ${projectDir}/continuous-seed-test
      - configServer: *configServer
  - checkUpdates:
      - echo: ${datetime} - checkUpdates
      - loop:
          sleepTime: 5000
          jobs:
            - cmd:
                app: git
                args: -C ${projectDir}/continuous-seed-test reset --hard
            - cmd:
                app: git
                args: -C ${projectDir}/continuous-seed-test pull
            - if:
                type: contain!
                value: Already up to date
                jobs:
                  - configServer: *configServer